### ISSUE TITLE
.lean does not work with mongoose 5.0.0

### ISSUE THREAD

**Issue by jariwbh** [vkarpov15/mongoose-lean-virtuals#6]
Hi,

.lean with virtual was working fine when using mongoose 4.0. After updating it to mongoose 5.0.0, we get this error while using .lean with virtuals.

"Error: this.get is not a function",

**Comment by vkarpov15** [comment]
Thanks for reporting, opened an issue in the mongoose repo to track

**Comment by vkarpov15** [comment]
I can't reproduce this issue, the following script works fine. Can you modify it to reproduce your issue?

```javascript
const mongoose = require('mongoose');
const mongooseLeanVirtuals = require('./');

const schema = new mongoose.Schema({
  name: String
});
schema.virtual('lowercaseName').get(function() {
  return this.name.toLowerCase();
});
schema.plugin(mongooseLeanVirtuals);

const Model = mongoose.model('t1', schema);

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await Model.deleteMany({});
  const doc = await Model.create({ name: 'Val' });

  console.log(await Model.findById(doc._id).lean({ virtuals: true }));
  console.log('done');
}
```

**Comment by jariwbh** [comment]
Hi,

Issue occured if we used alias in schema.

you can reproduce error with this change.


const mongoose = require('mongoose');
const mongooseLeanVirtuals = require('mongoose-lean-virtuals');

const schema = new mongoose.Schema({
  name: { 
    type: String,
    alias: 'Member Name'
  },
});
schema.virtual('lowercaseName').get(function() {
  return this.name.toLowerCase();
});
schema.plugin(mongooseLeanVirtuals);

const Model = mongoose.model('t1', schema);

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await Model.deleteMany({});
  const doc = await Model.create({ name: 'Val' });

  console.log(await Model.findById(doc._id).lean({ virtuals: true }));
  console.log('done');
}

**Comment by vmattila** [comment]
Would it be possible to inject this fix also to work in mongoose 4.* branch?

**Comment by vkarpov15** [comment]
@vmattila what is preventing you from upgrading to Mongoose 5.x?

**Comment by vmattila** [comment]
@vkarpov15 unfortunately the database environment is still on MongoDB 2.6, and it requires 4.x version (https://mongoosejs.com/docs/compatibility.html). That saying, 2.6 is already EOL, so I understand if fixing 4.* is not feasible.

**Comment by vkarpov15** [comment]
@vmattila we just shipped 4.13.20 with the fix :+1: Normally we don't backport fixes to 4.x though, so I would strongly recommend upgrading your MongoDB server.
